banner: |
    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–ˆ  â–ˆ   â–ˆ  â–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–ˆ
      â–ˆ   â–ˆ   â–ˆ â–ˆ   â–ˆ â–ˆ   â–ˆ   â–ˆ  â–ˆ    
      â–ˆ   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆâ–ˆ  â–ˆ   â–ˆ   â–ˆ   â–ˆâ–ˆâ–ˆ 
    â–ˆ â–ˆ   â–ˆ   â–ˆ â–ˆ  â–ˆ   â–ˆ â–ˆ    â–ˆ      â–ˆ
     â–ˆâ–ˆ   â–ˆ   â–ˆ â–ˆ   â–ˆ   â–ˆ    â–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–ˆ
# åœ°å€: https://github.com/Jarv1s0/Proxy_Script
# ç‰ˆæœ¬: v2.0
# æ›´æ–°: 2026 å¹´ 1 æœˆ 27 æ—¥

# ==================== æ ¸å¿ƒé…ç½® ====================
# åŸºç¡€é…ç½®
mode: rule
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: warning
bind-address: '*'
find-process-mode: 'always'
global-client-fingerprint: chrome
keep-alive-interval: 15
keep-alive-idle: 600

# TUNæ¨¡å¼é…ç½®
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
    
# DNSé…ç½®
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 119.29.29.29
    - 180.184.1.1
    - 223.5.5.5
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter:
    - rule-set:Direct
    - rule-set:Private
    - rule-set:China
    - rule-set:fakeip-filter


# ç®¡ç†é¢æ¿é…ç½®
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
external-ui-name: zashboard
external-ui: ui
external-controller: 127.0.0.1:9090
secret: ''  

# å®éªŒæ€§åŠŸèƒ½
experimental:
  quic-go-disable-gso: true  
  
# é…ç½®å­˜å‚¨
profile:
  store-selected: true
  store-fake-ip: true

# æµé‡å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    
 # ==================== é”šç‚¹é…ç½® ====================   
# é”šç‚¹å®šä¹‰
UrlTest: &UrlTest {type: url-test, interval: 200, lazy: true, url: 'https://www.google.com/generate_204', hidden: true, include-all: true }
Select: &Select { type: select, hidden: false, include-all: true }
Global_settings: { exclude_regex: &global_exclude "AHK|æ’é™¤1|æ’é™¤2|5x|å‰©ä½™æµé‡|è¿‡æœŸ|å›å›½|ç¾¤|å®˜ç½‘|å®¢æœ|è®¢é˜…|æµé‡" }
# åœ°ç†ä½ç½®åŒ¹é…é”šç‚¹
filters:
  - &FilterHK '(?i)æ¸¯|ğŸ‡­ğŸ‡°|HK|Hong|HKG'
  - &FilterSG '(?i)å¡|ğŸ‡¸ğŸ‡¬|SG|Sing|SIN|XSP'
  - &FilterJP '(?i)æ—¥|ğŸ‡¯ğŸ‡µ|JP|Japan|NRT|HND|KIX|CTS|FUK'
  - &FilterKR '(?i)éŸ©|ğŸ‡°ğŸ‡·|éŸ“|é¦–å°”|KR|KOR|Korea'
  - &FilterUS '(?i)ç¾|ğŸ‡ºğŸ‡¸|\bUS\b|USA|SJC|JFK|LAX|ORD|SFO'
  - &FilterTW '(?i)å°|ğŸ‡¹ğŸ‡¼|TW|tai|TPE|TSA|KHH'
  - &FilterEU '(?i)å¾·|æ³•|è‹±|æ„|è·|ç‘|ğŸ‡ªğŸ‡º|FRA|CDG|LHR|AMS'

# ==================== ä»£ç†ç­–ç•¥ç»„ ====================
#ä»£ç†ç»„
proxy-groups:
  # --- é¡¶å±‚ä¸šåŠ¡åˆ†ç»„ ---
  - { name: Proxy, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ, ALL, DIRECT], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Rocket.png }
  - { name: YouTube, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png }
  - { name: AI, type: select, proxies: [ç¾å›½, æ–°åŠ å¡, å°æ¹¾, æ—¥æœ¬, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/AI.png }
  - { name: Games, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ, DIRECT], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Steam.png }
  - { name: Google, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Google_Search.png } 
  - { name: GitHub, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/GitHub.png }
  - { name: Telegram, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Telegram.png }

  # --- åº•å±‚åœ°åŒºç­›é€‰ç»„ ---
  - { name: é¦™æ¸¯, <<: *UrlTest, filter: *FilterHK, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png }
  - { name: å°æ¹¾, <<: *UrlTest, filter: *FilterTW, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Taiwan.png }
  - { name: æ—¥æœ¬, <<: *UrlTest, filter: *FilterJP, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png }
  - { name: æ–°åŠ å¡, <<: *UrlTest, filter: *FilterSG, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png }
  - { name: éŸ©å›½, <<: *UrlTest, filter: *FilterKR, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Korea.png }
  - { name: ç¾å›½, <<: *Select, filter: *FilterUS, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png }
  - { name: æ¬§ç›Ÿ, <<: *UrlTest, filter: *FilterEU, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/European_Union.png } 
  - { name: ALL, type: select, include-all: true, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Global.png }

# ==================== è§„åˆ™é›† ====================
# è§„åˆ™é›†è¡Œä¸ºæ¨¡æ¿
BehaviorDN: &BehaviorDN {type: http, behavior: domain, format: mrs, interval: 86400, proxy: Proxy}
BehaviorIP: &BehaviorIP {type: http, behavior: ipcidr, format: mrs, interval: 86400, proxy: Proxy}

# è§„åˆ™æä¾›è€…
rule-providers:  
  # åŸŸåè§„åˆ™
  Tracking:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Tracking.mrs}
  Advertising:    {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Advertising.mrs} 
  Direct:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Direct.mrs}
  Private:        {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/private.mrs}
  Download:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Download.mrs}
  fakeip-filter:  {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs}
  AI:             {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs} 
  GitHub:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/GitHub.mrs}    
  Telegram:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Telegram.mrs}
  GamesCN:        {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games-cn.mrs} 
  Games:          {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games.mrs}
  YouTube:        {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/youtube.mrs}
  AppleCN:        {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/AppleCN.mrs}
  Google:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Google.mrs}
  MicrosoftCN:    {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/microsoft-cn.mrs}  
  Proxy:          {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Proxy.mrs}
  China:          {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs}
  # IPè§„åˆ™
  AdvertisingIP:  {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Advertising.mrs}
  PrivateIP:      {<<: *BehaviorIP, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.mrs}
  AIIP:           {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/AI.mrs}
  TelegramIP:     {<<: *BehaviorIP, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs}   
  GoogleIP:       {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Google.mrs}  
  ProxyIP:        {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Proxy.mrs} 
  ChinaIP:        {<<: *BehaviorIP, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.mrs}
  
# ==================== è§„åˆ™è·¯ç”± ====================  
rules:
  # 1. ä¼˜å…ˆå¤„ç†ç‰¹å®šåŸŸåå…³é”®å­— (DomainSet/Keyword)
  - DOMAIN-KEYWORD,1ytsub,DIRECT
  - DOMAIN-KEYWORD,jarv1s,Proxy
  - PROCESS-NAME,dota2.exe,DIRECT
  - PROCESS-NAME,language_server_windows_x64.exe,AI # Antigravity
  - PROCESS-NAME,Antigravity.exe,AI # Antigravity 
  # æ‹¦æˆªè§„åˆ™
  - RULE-SET,Tracking,REJECT
  - RULE-SET,Advertising,REJECT
  - AND,((DST-PORT,443),(NETWORK,UDP),(NOT,((GEOIP,CN)))),REJECT  # é˜»æ­¢æµ·å¤– QUIC  
  # åŸŸåè§„åˆ™
  - RULE-SET,Private,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,GamesCN,DIRECT
  - RULE-SET,Download,DIRECT
  - RULE-SET,AppleCN,DIRECT
  - RULE-SET,MicrosoftCN,DIRECT
  - RULE-SET,AI,AI
  - RULE-SET,GitHub,GitHub
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Games,Games
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Google,Google

  - RULE-SET,Proxy,Proxy
  - RULE-SET,China,DIRECT
  # IPè§„åˆ™
  - RULE-SET,AdvertisingIP,REJECT,no-resolve
  - RULE-SET,PrivateIP,DIRECT,no-resolve
  - RULE-SET,AIIP,AI,no-resolve
  - RULE-SET,TelegramIP,Telegram,no-resolve
  - RULE-SET,GoogleIP,Google,no-resolve
  - RULE-SET,ProxyIP,Proxy,no-resolve
  - RULE-SET,ChinaIP,DIRECT,no-resolve
  - MATCH,Proxy
